version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
environment:
   sonartoken:
     secure: DRj3fNloTg/lBt6VibH5zebVnMv0pF7+lXBkaR28lR4Iu3g4KSyXl6Vn+Ni/Nx96
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\scripts\Build.ps1
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: 3FtJ1e9nPNg4u0vBuJNLYgLjo1brWrpi8sgRscqsEaPAuqOmjxKqSsx/W4xMx3JH
  on:
    branch: master
    appveyor_repo_tag: true